# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1df54ec23fb6ff980d7aa2f6d6c010685c78eaba02cf2d58e46675ad80d28f3bf3404b229edec9030856942293c82716e1a6a390117d10247522bace7389232

test:
  secret_key_base: 10cd69b850f5bda87c90fb77e7a01ef7790bf982e836aa5d954b8767c4ce24ab7a1ad2a8c5dcdb658e21322dbed17a4250e31229d82052c1c31619149ab5baeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
